### ISSUE TITLE
emuiibo找不到

### ISSUE THREAD

**Issue by lwj-java** [AK478BB/AK-Tesla#1]
请问下，amiibo放入之后，打开特斯拉插件说找不到amiibo

**Comment by lwj-java** [comment]
深海打开emuiibo后，重启。但是从特斯拉控制台插件中，看到emuiibo还是off

**Comment by AK478BB** [comment]
> 深海打开emuiibo后，重启。但是从特斯拉控制台插件中，看到emuiibo还是off

emuiibo插件即使在启动后，也需先预览sd卡emuiibo/amiibo/中的amiibo代码文件，再打开游戏可以使用。之前的emuiibo适配16.0.0系统的dev版本，是因为必须新建emuiibo/miis/才可以正常启动，但是正式版改成自动建miis，如果是手动创建的，可能导致权限冲突无法启动emuiibo插件，请删除emuiibo/miis/
